name: Preview Release

on:
  push:
    branches:
      - master
      - build/release-automatization

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'opres-help-preview'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
